apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: botium-box
  labels:
    name: redis
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: redis
      app: botium-box
      tier: backend      
  template:
    metadata:
      labels:
        name: redis
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - name: redis-6379
              containerPort: 6379	  
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: botium-box
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    name: redis
    app: botium-box