apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma
  namespace: botium-box
  labels:
    name: prisma
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: prisma
      app: botium-box
      tier: backend  
  template:
    metadata:
      labels:
        name: prisma
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: prisma
          image: botium/prisma:2.9.0
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: botium-box
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma
    app: botium-box